apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functions.justfaas.com
spec:
  group: justfaas.com
  scope: Namespaced
  names:
    plural: functions
    singular: function
    kind: Function
    shortNames:
      - func
      - funcs
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                port:
                  type: number
                env:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                      valueFrom:
                        type: object
                        properties:
                          configMapKeyRef:
                            type: object
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                              optional:
                                type: boolean
                          fieldRef:
                            type: object
                            properties:
                              apiVersion:
                                type: string
                              fieldPath:
                                type: string
                          secretKeyRef:
                            type: object
                            properties:
                              key:
                                type: string
                              name:
                                type: string
                              optional:
                                type: boolean
                ingress:
                  type: object
                  required:
                    - host
                  properties:
                    host:
                      type: string
                    path:
                      type: string
                    tls:
                      type: object
                      properties:
                        issuerRef:
                          type: object
                          properties:
                            name:
                              type: string
                            kind:
                              type: string
                secrets:
                  type: array
                  items:
                    type: string
                configMaps:
                  type: array
                  items:
                    type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workspaces.justfaas.com
spec:
  group: justfaas.com
  scope: Namespaced
  names:
    plural: workspaces
    singular: workspace
    kind: Workspace
    shortNames:
      - ws
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
